package com.patternforge.api.rest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.patternforge.jooq.tables.records.PatternsRecord;
import com.patternforge.storage.repository.ConversationalPatternRepository;
import com.patternforge.storage.repository.PatternRepository;
import com.patternforge.storage.repository.ProjectRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Generates a dynamic, always-current standards document from the PatternForge knowledge base.
 *
 * <p>This replaces the need to copy-paste {@code AGENTS.md} or {@code CLAUDE.md} into every
 * project. Agents can call {@code GET /api/standards} instead and receive the same information
 * tailored to the project and language, without any static file to maintain.
 *
 * <p>The document is formatted as Markdown, ready to inject into any agent's system prompt
 * or to curl into a local file.
 *
 * <h2>Usage</h2>
 * <pre>
 * # Print to terminal
 * curl "http://localhost:15550/api/standards?projectPath=$(pwd)&amp;language=java"
 *
 * # Save as local AGENTS.md (optional — only if your tool needs a file)
 * curl -s "http://localhost:15550/api/standards?projectPath=$(pwd)&amp;language=java" \
 *      > .agent/STANDARDS.md
 * </pre>
 *
 * <p>Via MCP, agents call the {@code get_standards} tool which hits this same endpoint.
 */
@RestController
@RequestMapping("/api/standards")
@RequiredArgsConstructor
@Slf4j
public class StandardsController {

    private final PatternRepository patternRepository;
    private final ProjectRepository projectRepository;
    private final ConversationalPatternRepository conversationalPatternRepository;
    private final ObjectMapper objectMapper;

    /**
     * Generates a complete standards document for a project.
     *
     * @param projectPath absolute path to the project root (used for project-specific patterns)
     * @param language    primary language of the project (used to filter patterns)
     * @return formatted Markdown standards document
     */
    @GetMapping(produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> generateStandards(
            @RequestParam String projectPath,
            @RequestParam(defaultValue = "java") String language) {

        log.info("Generating standards for projectPath={}, language={}", projectPath, language);

        List<PatternsRecord> globalPatterns = patternRepository.findGlobalPatterns();
        List<PatternsRecord> allPatterns = patternRepository.findAll();

        // Project-specific: patterns whose source references this project path, or marked as project-standard
        List<PatternsRecord> projectPatterns = allPatterns.stream()
            .filter(p -> Boolean.FALSE.equals(p.getIsGlobalStandard()))
            .filter(p -> Boolean.TRUE.equals(p.getIsProjectStandard())
                || matchesProject(p, projectPath))
            .toList();

        // Language-relevant patterns (global ones matching language, not already shown)
        List<PatternsRecord> languagePatterns = globalPatterns.stream()
            .filter(p -> matchesLanguage(p, language))
            .toList();

        String document = buildStandardsDocument(
            projectPath, language,
            globalPatterns, projectPatterns, languagePatterns
        );

        return ResponseEntity.ok(document);
    }

    // ─────────────────────────────────────────────────────────────
    // Document generation
    // ─────────────────────────────────────────────────────────────

    private String buildStandardsDocument(
            String projectPath,
            String language,
            List<PatternsRecord> globalPatterns,
            List<PatternsRecord> projectPatterns,
            List<PatternsRecord> languagePatterns) {

        StringBuilder doc = new StringBuilder();

        // Header
        doc.append("# Coding Standards — Served by PatternForge\n\n");
        doc.append("> Auto-generated from the PatternForge knowledge base. Always current.\n");
        doc.append("> Do NOT edit this file manually — update patterns via PatternForge instead.\n\n");
        doc.append("**Project**: `").append(projectPath).append("`  \n");
        doc.append("**Language**: ").append(language).append("  \n");
        doc.append("**Patterns loaded**: ").append(globalPatterns.size() + projectPatterns.size()).append("\n\n");
        doc.append("---\n\n");

        // Before-every-task block
        doc.append("## Before Every Task\n\n");
        doc.append("Query PatternForge for relevant patterns and workflow:\n\n");
        doc.append("```bash\n");
        doc.append("curl -s -X POST http://localhost:15550/api/patterns/query \\\n");
        doc.append("  -H \"Content-Type: application/json\" \\\n");
        doc.append("  -d '{\n");
        doc.append("    \"task\": \"<describe your task here>\",\n");
        doc.append("    \"language\": \"").append(language).append("\",\n");
        doc.append("    \"projectPath\": \"").append(projectPath).append("\"\n");
        doc.append("  }' | jq '{patterns: [.patterns[].title], steps: [.workflow.steps[].action]}'\n");
        doc.append("```\n\n");
        doc.append("- Apply every pattern returned.\n");
        doc.append("- Follow `workflow.steps` in order. Do not skip steps.\n");
        doc.append("- Block on any `qualityGates` with `blocking: true`.\n\n");
        doc.append("---\n\n");

        // Global standards
        if (!globalPatterns.isEmpty()) {
            doc.append("## Global Standards (Always Apply)\n\n");
            doc.append("These patterns apply to all projects and must always be followed.\n\n");
            appendPatternList(doc, globalPatterns, language);
            doc.append("\n");
        }

        // Language-specific from global
        if (!languagePatterns.isEmpty() && languagePatterns.stream().anyMatch(p -> !globalPatterns.contains(p))) {
            doc.append("## ").append(capitalize(language)).append("-Specific Standards\n\n");
            List<PatternsRecord> languageOnly = languagePatterns.stream()
                .filter(p -> !globalPatterns.contains(p))
                .toList();
            if (!languageOnly.isEmpty()) {
                appendPatternList(doc, languageOnly, language);
                doc.append("\n");
            }
        }

        // Project-specific
        if (!projectPatterns.isEmpty()) {
            doc.append("## Project-Specific Standards\n\n");
            doc.append("These patterns are specific to this project.\n\n");
            appendPatternList(doc, projectPatterns, language);
            doc.append("\n");
        }

        if (globalPatterns.isEmpty() && projectPatterns.isEmpty()) {
            doc.append("## No Patterns Stored Yet\n\n");
            doc.append("Seed patterns by running:\n\n");
            doc.append("```bash\n");
            doc.append("curl -s -X POST http://localhost:15550/api/patterns/extract \\\n");
            doc.append("  -H \"Content-Type: application/json\" \\\n");
            doc.append("  -d '{\"filePath\": \"").append(projectPath).append("/AGENTS.md\",\n");
            doc.append("       \"projectPath\": \"").append(projectPath).append("\"}'\n");
            doc.append("```\n\n");
        }

        // Capture pattern section
        doc.append("---\n\n");
        doc.append("## Teaching PatternForge New Standards\n\n");
        doc.append("When you establish a new standard during a session, capture it:\n\n");
        doc.append("```bash\n");
        doc.append("curl -s -X POST http://localhost:15550/api/patterns/capture \\\n");
        doc.append("  -H \"Content-Type: application/json\" \\\n");
        doc.append("  -d '{\n");
        doc.append("    \"description\": \"Always use Result<T> for error handling in services\",\n");
        doc.append("    \"source\": \"user_explicit\",\n");
        doc.append("    \"projectPath\": \"").append(projectPath).append("\",\n");
        doc.append("    \"codeExample\": \"Result<User> user = userService.findById(id);\",\n");
        doc.append("    \"rationale\": \"Explicit error handling without exceptions\"\n");
        doc.append("  }'\n");
        doc.append("```\n\n");
        doc.append("Patterns captured 3+ times auto-promote to project standards.\n\n");

        // MCP footer
        doc.append("---\n\n");
        doc.append("## MCP Integration\n\n");
        doc.append("If your agent supports MCP, add this to `~/.claude.json` or `.mcp.json`:\n\n");
        doc.append("```json\n");
        doc.append("{\n");
        doc.append("  \"mcpServers\": {\n");
        doc.append("    \"patternforge\": {\n");
        doc.append("      \"type\": \"http\",\n");
        doc.append("      \"url\": \"http://localhost:8765/mcp\"\n");
        doc.append("    }\n");
        doc.append("  }\n");
        doc.append("}\n");
        doc.append("```\n\n");
        doc.append("Available tools: `query_patterns`, `capture_pattern`, `get_standards`, `record_usage`\n");

        return doc.toString();
    }

    private void appendPatternList(StringBuilder doc, List<PatternsRecord> patterns, String language) {
        for (PatternsRecord pattern : patterns) {
            doc.append("### ").append(pattern.getTitle()).append("\n\n");

            if (Objects.nonNull(pattern.getDescription()) && !pattern.getDescription().isBlank()) {
                doc.append(pattern.getDescription()).append("\n\n");
            }

            if (Objects.nonNull(pattern.getWhenToUse()) && !pattern.getWhenToUse().isBlank()) {
                doc.append("**When to use**: ").append(pattern.getWhenToUse()).append("\n\n");
            }

            // Code example for this language
            if (Objects.nonNull(pattern.getCodeExamples())) {
                try {
                    Map<String, Object> examples = objectMapper.readValue(
                        pattern.getCodeExamples().data(),
                        new TypeReference<Map<String, Object>>() {}
                    );
                    Object example = examples.get(language);
                    if (Objects.isNull(example)) {
                        // Try first available language
                        example = examples.values().stream().findFirst().orElse(null);
                    }
                    if (Objects.nonNull(example)) {
                        doc.append("```").append(language).append("\n");
                        doc.append(example.toString().trim()).append("\n");
                        doc.append("```\n\n");
                    }
                } catch (Exception exception) {
                    log.debug("Failed to parse code examples for pattern: {}", pattern.getPatternId());
                }
            }

            // Anti-patterns
            if (Objects.nonNull(pattern.getAntiPatterns()) && pattern.getAntiPatterns().length > 0) {
                doc.append("**Anti-patterns to avoid**:\n");
                for (String antiPattern : pattern.getAntiPatterns()) {
                    doc.append("- ").append(antiPattern).append("\n");
                }
                doc.append("\n");
            }
        }
    }

    // ─────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────

    private boolean matchesLanguage(PatternsRecord pattern, String language) {
        if (Objects.isNull(pattern.getLanguages()) || pattern.getLanguages().length == 0) {
            return true; // Language-agnostic patterns apply everywhere
        }
        return Arrays.asList(pattern.getLanguages()).contains(language);
    }

    private boolean matchesProject(PatternsRecord pattern, String projectPath) {
        if (Objects.isNull(pattern.getSource()) || pattern.getSource().isBlank()) {
            return false;
        }
        return pattern.getSource().contains(projectPath);
    }

    private String capitalize(String input) {
        if (Objects.isNull(input) || input.isBlank()) {
            return input;
        }
        return Character.toUpperCase(input.charAt(0)) + input.substring(1);
    }
}
